version: '3'
services:
  nginx:
    image: nginx:latest #使用nginx官方最新稳定版镜像
    ports:
      - "8080:80" #映射宿主机8080端口到容器80端口
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf #映射宿主机nginx配置文件到容器nginx配置文件
      - ./:/var/www/html #映射当前目录到nginx网站目录
    depends_on:
      - php #链接PHP容器
  php:
    image: php:7.4-fpm #使用官方PHP7.4版本镜像
    volumes:
      - ./:/var/www/html #映射当前目录作为PHP目录
